apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  restartPolicy: Never
  containers:
    - name: cuda-container
      image: quay.io/rh-ee-srehman/llm-train:v5
      nodeSelector:
        run: ai
      resources:
        requests:
          memory: "40Gi"
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
          memory: "40Gi"